parameter_list =   ['Pressure reduced to MSL',
                    'Visibility',
                    '224',
                    'Wind speed (gust)',
                    '2',
                    'Vertical velocity (pressure)',
                    'Vertical velocity (geometric)',
                    'Absolute vorticity',
                    'Turbulent kinetic energy',
                    'Soil temperature',
                    'Soil moisture content',
                    'Snow depth',
                    'Dew point temperature',
                    'Total precipitation',
                    'Convective precipitation',
                    'Water equivalent of accumulated snow depth',
                    '194',
                    'Surface roughness',
                    '197',
                    '196',
                    'Vegetation',
                    '198',
                    'Soil type',
                    '201',
                    '195',
                    'Convective inhibition',
                    'Precipitable water',
                    'Storm relative helicity',
                    'Vertical u-component shear',
                    'Vertical v-component shear',
                    'Specific humidity',
                    'Pressure',
                    'Geopotential height',
                    'Parcel lifted index (to 500 hPa)',
                    'Temperature',
                    'u-component of wind',
                    'v-component of wind',
                    'Convective available potential energy',
                    'Convective inhibition',
                    '196',
                    'Relative humidity',
                    'Land cover (0=land, 1=sea)',
                    'Ice cover',
                    'Albedo',
                    'Sensible heat net flux',
                    'Latent heat net flux',
                    'Total cloud cover']
